services:
  - type: web
    name: asta-bot
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 5000
      - key: PREFIX
        value: .
