import axios from 'axios';
import fs from 'fs-extra';
import path from 'path';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const TEMP_DIR = path.join(__dirname, '../../cache/suno_temp');

const HF_API = 'https://api-inference.huggingface.co/models/facebook/musicgen-small';

function parsePrompt(text) {
    text = text.trim();
    let genre = '';
    let artist = '';

    // Extract "by <artist>"
    const byMatch = text.match(/\bby\s+([A-Za-z0-9_\s]+)$/i);
    if (byMatch) {
        artist = byMatch[1].trim();
        text = text.slice(0, byMatch.index).trim();
    }

    // Extract genre keywords
    const possibleGenres = ['afrobeat', 'drill', 'hip hop', 'hiphop', 'rap', 'trap', 'pop', 'rock', 'rnb',
        'r&b', 'jazz', 'blues', 'reggae', 'dancehall', 'country', 'edm', 'house', 'techno',
        'amapiano', 'gospel', 'soul', 'funk', 'lofi', 'lo-fi', 'classical', 'metal', 'punk',
        'alternative', 'indie', 'folk', 'latino', 'kpop', 'afropop', 'highlife', 'soca',
        'dubstep', 'grime'];

    for (const g of possibleGenres) {
        const idx = text.toLowerCase().indexOf(g);
        if (idx !== -1) {
            genre = text.slice(idx, idx + g.length);
            text = text.slice(0, idx).trim() + ' ' + text.slice(idx + g.length).trim();
            break;
        }
    }

    text = text.replace(/\s+/g, ' ').trim();
    if (!text) text = 'a song';

    return { prompt: text, genre, artist };
}

export default {
    name: 'suno',
    aliases: ['songgen', 'musicgen', 'musica'],
    category: 'ai',
    description: 'Generate music using AI by prompt and style',
    usage: 'suno <description> <genre> by <artist>',
    example: 'suno I love you afrobeat by Kenzy',
    cooldown: 60,
    args: true,
    minArgs: 1,

    async execute({ sock, message, from, args }) {
        const text = args.join(' ').trim();
        if (!text) {
            return await sock.sendMessage(from, {
                text: '🎵 *Music Generator*\n\nUsage:\n`.suno <description> <genre> by <artist>`\n\nExample:\n`.suno I love you afrobeat by Kenzy`'
            }, { quoted: message });
        }

        const { prompt, genre, artist } = parsePrompt(text);

        await sock.sendMessage(from, { react: { text: '🎵', key: message.key } });

        const statusMsg = await sock.sendMessage(from, {
            text: `🎵 *Generating Music...*\n\n📝 ${prompt}\n🎶 ${genre || 'auto'}\n👤 ${artist || 'unknown'}\n\n⏳ This may take 30-60 seconds...`
        }, { quoted: message });

        try {
            await fs.ensureDir(TEMP_DIR);

            // Build a rich music description for MusicGen
            let hfPrompt = `${genre ? genre + ' style, ' : ''}${prompt}`;
            if (artist) hfPrompt += `, in the style of ${artist}`;
            hfPrompt += ', high quality music';

            // Call Hugging Face MusicGen
            const resp = await axios.post(HF_API, {
                inputs: hfPrompt,
                parameters: {
                    max_new_tokens: 256,
                    temperature: 0.9,
                    top_k: 250,
                    top_p: 0.95
                }
            }, {
                responseType: 'arraybuffer',
                timeout: 120000,
                headers: {
                    'User-Agent': 'Mozilla/5.0',
                    'Accept': 'audio/wav,audio/mpeg,*/*'
                }
            });

            const audioBuf = Buffer.from(resp.data);
            if (!audioBuf || audioBuf.length < 1024) {
                throw new Error('Empty response from music generator');
            }

            const outPath = path.join(TEMP_DIR, `suno_${Date.now()}.mp3`);
            await fs.writeFile(outPath, audioBuf);

            const caption = `🎵 *${prompt}*\n` +
                (genre ? `🎶 Genre: ${genre}\n` : '') +
                (artist ? `👤 Artist: ${artist}\n` : '') +
                `🤖 Generated by AI`;

            await sock.sendMessage(from, {
                audio: { url: outPath },
                mimetype: 'audio/mpeg',
                fileName: `${prompt.replace(/[^a-zA-Z0-9]/g, '_')}.mp3`,
                ptt: false,
                caption: caption
            }, { quoted: message });

            // Clean up
            await fs.remove(outPath).catch(() => {});

            await sock.sendMessage(from, { delete: statusMsg.key });
            await sock.sendMessage(from, { react: { text: '✅', key: message.key } });

        } catch (e) {
            await sock.sendMessage(from, { delete: statusMsg.key });
            await sock.sendMessage(from, { react: { text: '❌', key: message.key } });
            let msg = `❌ Error: ${e.message}`;
            if (e.response?.status === 503) {
                msg = '❌ Model is loading. Try again in a moment.';
            }
            await sock.sendMessage(from, { text: msg }, { quoted: message });
        }
    }
};
